int controller_loadFromText(char* path, LinkedList* pArrayListLibros);
//int controller_loadFromBinary(char* path , LinkedList* pArrayListEmployee);
//int controller_addEmployee(LinkedList* pArrayListEmployee);
//int controller_editEmployee(LinkedList* pArrayListEmployee);
//int controller_removeEmployee(LinkedList* pArrayListEmployee);
int controller_ListEnvios(LinkedList* pArrayListEnvios);
//int controller_costoTipoEntrega(void* p);
//int controller_sortEmployee(LinkedList* pArrayListEmployee);
int controller_saveAsText(char* path, LinkedList* pArrayListLibros);
//int controller_saveAsBinary(char* path , LinkedList* pArrayListEmployee);
int idMaxArray(LinkedList* pArrayLibros);
int controller_costoTipoEntrega(void* p);
int controller_aumentoPorKilometros(void* p);
//int controller_menosDeCienHoras(void* p);
int costoTipoEntrega(void* p);
int imprimirTipo(LinkedList *lista);
